### ISSUE TITLE
не запускается 

### ISSUE THREAD

**Issue by imkillplz** [wasiejen/Free-Snap-Tap#20]
пробовал все методы запуска так и не получилось файл просто даёт ошибку либо просто не запускается так нечего и не смог сделать

**Comment by wasiejen** [comment]
Hello and thanks for trying to start the program.

Without any more information about your system you are trying to run it on or what the error actually is, it is nearly impossible to help you.

If you are on Linux then it will not work. Simple as that.
For any more detailed guesses I need more information. ;-)

Best regards

**Comment by imkillplz** [comment]
windows
![83c4d464-d7b5-4b3d-883f-91724f5637b4](https://github.com/user-attachments/assets/45bde6b1-3f18-4ea0-9ce3-f2e3944d027a)

**Comment by wasiejen** [comment]
See [link to readme](https://github.com/wasiejen/Free-Snap-Tap?tab=readme-ov-file#requirements-if-you-want-to-use-the-py-file-directly) for a complete overview of how to start the py files directly.

In your case you need to install the pynput package first. 
Open a command line window (win cmd enter) and type in:

```bash
pip install pynput
```
or navigate to Free-Snap-Tap folder and type in:

```bash
pip install -r requirements.txt
```

Then try again. :-D
