### ISSUE TITLE
Linux not working 

### ISSUE THREAD

**Issue by erqem07** [wasiejen/Free-Snap-Tap#3]
hello i use linux manjaro and it isnt working. i donno why

**Comment by wasiejen** [comment]
Hello, thanks for testing this program. 
I only tested it on windows 10 and I am using the win32_event_filter for key event handling. 
Maybe this has no linux equivalent. Was too lazy to set up a small ubuntu vm jet. xD

# Answer:

I digged a bit into pynput (package used for this program) to find an answer and found it:

> https://pynput.readthedocs.io/en/latest/faq.html

"If your backend of choice is not listed below, it does not support suppression of specific events."

And it only lists MacOS and Windows as supporting supression of specific key events - and that is exactly what I do with this program - I only supress some of the key events and let everything else be. The pynput implementation in linux (or maybe linux as general - i don't know jet) only seems to support general/full supression of events - no seletive supression that is needed for this program.

So sry - with the actual implementation it will not work on linux.

Will add that to the readme.

**Comment by wasiejen** [comment]
V0.37 Linux v1 version is online. 
Not yet tested on linux. theoretically it might work. :-)

Would be helpful for me if you could test it.

**Comment by wasiejen** [comment]
With V0.50 removal of any implementation to support linux - most of the functionality would not work because of the missing possibility to supress key events on linux in general.
