### ISSUE TITLE
0.9.4 tap groups is not working anymore.

### ISSUE THREAD

**Issue by dvgmdvgm** [wasiejen/Free-Snap-Tap#41]
Hello! After 0.9.4 update if i press A and hold D my A input is not canceled as should be.

**Comment by wasiejen** [comment]
thanks for testing :-)

**Comment by dvgmdvgm** [comment]
> thanks for testing :-)

Just rebuilt new exe and it's working) thanks.
I just change plus and minus syntax for macros because for me it's more readable when + mean pressed and - is realesed. 
Except of this everything is okay.
