### ISSUE TITLE
[Request] Macros applied by Focus only

### ISSUE THREAD

**Issue by dvgmdvgm** [wasiejen/Free-Snap-Tap#47]
At latest release was added good feature as Groups applied by focus app only but we need to separate macros as well. Because in CS2 i use Space button to run macros and now i can't use my PC to type some text because every time i pressing space i type a lot of different symbols. Can you make the same to Macros as Groups?

**Comment by dvgmdvgm** [comment]
My bad. I comment my macros. So now it's works as i want i guess

**Comment by wasiejen** [comment]
macros will only apply to all as default if you have no <focus> set. if you set your focus at the start of the config files it will activate everything just in focus app like normal. 

Do you use the start argument focusapp? 
That is not compatible any more - should probably remove the option entirely xD
