### ISSUE TITLE
Backspace is not holdable if focus app

### ISSUE THREAD

**Issue by dvgmdvgm** [wasiejen/Free-Snap-Tap#50]
Hello. Want to report if i playing CS and it's in focus list i can't erase several symbols by holding backspace butting. Only latest symbol can be removed so i need to press backspace 5 times to remove 5 characters instead of holding.

**Comment by wasiejen** [comment]
Heyho,

yeah that is currently the intended behavior for ALL keys - no repeating allowed atm. :-D
Just to prevent that holding a key will launch the same macro over and over.

I think I can come up with a more elegant solution by just allowing the first press/release key event be able to trigger a macro. have to see what else might be influenced by that change in hold key handling.

Notes for myself: 
- vk_codes with not physical representation should be excluded (vk_codes <=0)
- also have to prevent continuous actualization of key press/release times of repeated key events by holding a key

**Comment by dvgmdvgm** [comment]
@wasiejen yesterday Faceit just update their ANtiCheat and every keys i build for macro doesn't work at all. For example i build macro for A & D сounterstrafing and i cannot move at all. Sadly

**Comment by wasiejen** [comment]
mhhh, my current guess would be that if Faceit has admin privileges, they are looking for simulated input and are not accepting it. 
Can you try rebinds also?  
Can you test if it works without the overlay indicator - maybe Faceit can recognize this and blocks everything from FST as a consequence.

If they suppress simulated keys:
If you use the tap groups with the actual version 1.0.2 than movement should work delayed but not the snap tap functionality at all if they ignore simulated key events.
That should work because the first press of a tap group will be suppressed and replaced by idealized simulated input and the following key_events while holding the key should get through, because these are real key_events.

For someone else it worked to also make a rebind on a different key to d: `. : d` and after hitting that it worked magically ... never heard of him after that. ^^

In general FST does not work as soon as the other program it should work with has admin privileges - that breaks FST in most cases.

**Comment by dvgmdvgm** [comment]
> mhhh, my current guess would be that if Faceit has admin privileges, they are looking for simulated input and are not accepting it. Can you try rebinds also? Can you test if it works without the overlay indicator - maybe Faceit can recognize this and blocks everything from FST as a consequence.
> 
> If they suppress simulated keys: If you use the tap groups with the actual version 1.0.2 than movement should work delayed but not the snap tap functionality at all if they ignore simulated key events. That should work because the first press of a tap group will be suppressed and replaced by idealized simulated input and the following key_events while holding the key should get through, because these are real key_events.
> 
> For someone else it worked to also make a rebind on a different key to d: `. : d` and after hitting that it worked magically ... never heard of him after that. ^^
> 
> In general FST does not work as soon as the other program it should work with has admin privileges - that breaks FST in most cases.

Sadly but my UAC is disabled and FACEIT AC running with admin every time. It's happened 2 days ago after their update of AC. So i can't check how it will work without AC running as administrator.

**Comment by dvgmdvgm** [comment]
> mhhh, my current guess would be that if Faceit has admin privileges, they are looking for simulated input and are not accepting it. Can you try rebinds also? Can you test if it works without the overlay indicator - maybe Faceit can recognize this and blocks everything from FST as a consequence.
> 
> If they suppress simulated keys: If you use the tap groups with the actual version 1.0.2 than movement should work delayed but not the snap tap functionality at all if they ignore simulated key events. That should work because the first press of a tap group will be suppressed and replaced by idealized simulated input and the following key_events while holding the key should get through, because these are real key_events.
> 
> For someone else it worked to also make a rebind on a different key to d: `. : d` and after hitting that it worked magically ... never heard of him after that. ^^
> 
> In general FST does not work as soon as the other program it should work with has admin privileges - that breaks FST in most cases.

Okay. I managed to run Faceit AC with no admin privileges by using psexec but FST still doesn't work with that latest updates. Any idea?

**Comment by wasiejen** [comment]
> Sadly but my UAC is disabled and FACEIT AC running with admin every time. It's happened 2 days ago after their update of AC. So i can't check how it will work without AC running as administrator. Doesn't work with previous version without indicator

thanks for letting me know that is does not seem to be the indicator :-)

> Okay. I managed to run Faceit AC with no admin privileges by using psexec but FST still doesn't work with that latest updates. Any idea?

Honestly I do not know atm. 
I do not know what psexec is capable of doing and thus if it really is running without admin privileges. 
It may as well be unrelated to the admin priv. FST itself is running without any admin priv and the underlying packages are able to distinguish simulated from real input and suppressing it system wide - so i imaging that this should be possible for any AC even without admin priv.

A workaround for games with admin priv that works for me (tested it right now) is to start FST also with admin rights.

**Comment by dvgmdvgm** [comment]
> > Sadly but my UAC is disabled and FACEIT AC running with admin every time. It's happened 2 days ago after their update of AC. So i can't check how it will work without AC running as administrator. Doesn't work with previous version without indicator
> 
> thanks for letting me know that is does not seem to be the indicator :-)
> 
> > Okay. I managed to run Faceit AC with no admin privileges by using psexec but FST still doesn't work with that latest updates. Any idea?
> 
> Honestly I do not know atm. I do not know what psexec is capable of doing and thus if it really is running without admin privileges. It may as well be unrelated to the admin priv. FST itself is running without any admin priv and the underlying packages are able to distinguish simulated from real input and suppressing it system wide - so i imaging that this should be possible for any AC even without admin priv.
> 
> A workaround for games with admin priv that works for me (tested it right now) is to start FST also with admin rights.

Any chance to try to find another input method? Cause AC just recognised simulating i guess.

**Comment by wasiejen** [comment]
At the moment it is not very likely that I will add another input method. I guess even if I could find a ready to use package for that, that also works out of the box with FACEIT AC, it is most likely just a stopgap measure until another update breaks it again. 
In the past I tested ctypes with windll for mouse_events - to my limited knowledge that is the most basic input method that is ready to be used. And it did not work with the problematic AC (have to look up which one it was).

There is a reason dedicated tools are implemented at driver level. :-)

My focus tbh is not on circumventing AC - that was more a side effect on requests in the past, but never a goal of this program. ^^

On the other side IF I find something that can be easily integrated I could go faster than expected.

Sry for the non answer ^^

**Comment by wasiejen** [comment]
If you have an Arduino we could try another option. 
The Arduino could be connected to the PC and act like a Human Input Device which is controlled by the python script to send input instead of the program. I think that could be implemented rather easily with a minimal script on the arduino, but needs a bit more effort on your side with flashing and connecting the Arduino correctly in the python script. That could potentially be AC proof.
