### ISSUE TITLE
[Request] add mor F** keys

### ISSUE THREAD

**Issue by dvgmdvgm** [wasiejen/Free-Snap-Tap#53]
Hello! Windows have up to F1-F24 keys but FST include only F12 so can you add more pls?
Cause we can bind something more and then simulate it

**Comment by wasiejen** [comment]
F13-F24 keys, interesting - never seen a keyboard that big :-D

try out [vk_codes.py](https://github.com/wasiejen/Free-Snap-Tap/blob/crosshair/vk_codes.py)
If you use the exe put it in the FST folder and hit built.bat (if you have cloned the folder) to generate the new exe file

**Comment by dvgmdvgm** [comment]
> F13-F24 keys, interesting - never seen a keyboard that big :-D
> 
> try out [vk_codes.py](https://github.com/wasiejen/Free-Snap-Tap/blob/crosshair/vk_codes.py) If you use the exe put it in the FST folder and hit built.bat (if you have cloned the folder) to generate the new exe file

It's not about keyboard but it still useful to bind F23 to switch some scene in OBS for example and then simulate it with your app. It's work with vk_codes but i don't want to rebuild it every update) I wanna download your exe because i'm lazy)))

**Comment by wasiejen** [comment]
The F13 to F24 keys are included in the current version 1.0.3. :-D
have fun ^^
