### ISSUE TITLE
Installation - Errors throw in despite following the instruction step by step

### ISSUE THREAD

**Issue by Scarlaid** [wasiejen/Free-Snap-Tap#65]
Hey, sorry if I'm asking the obvious here
I have Python 3.12, installed `pynput`, followed the [instruction](https://github.com/wasiejen/Free-Snap-Tap?tab=readme-ov-file#installation), but how much I tried to open the batch file, it just gives out error logs instead of working

I have tried reinstalling Python (not latest, this particular version because of game-related need), and then reinstall the requirements, re-downloaded 3 of the files inside the Release page, still no luck

What am I doing wrong here?
![explorer_PON9eBzyQ2](https://github.com/user-attachments/assets/ae9fe32b-3898-4f4b-97c1-8a0c9400e318)

**Comment by wasiejen** [comment]
Hello @Scarlaid 

In your config seems to be a line or a key definition with
`----------------------------------------`
that can not be converted to a corresponding vk_code.

You have done everything correctly the error IS in the example file xD :

```bash
### Example for Counters Strike with counterstrafing
-----------------------------   # <--- this line should be commented out via #

# should look like this
### Example for Counters Strike with counterstrafing
# -----------------------------
```

Will update example config file

**Comment by wasiejen** [comment]
[FSTconfig.txt](https://github.com/user-attachments/files/17415098/FSTconfig.txt)

Sry for the inconvenience, I cobbled the config together without testing it after. 

Corrected it and tested it now. 
If everything else is installed correctly then it should now work. :-)

**Comment by Scarlaid** [comment]
can confirm it worked now, thanks man 🤌
![image](https://github.com/user-attachments/assets/3f004b08-99cb-453e-98b5-f3bb33df0718)
